updated stuff

diff --git a/.goodies/custom_path/java_compile b/.goodies/custom_path/java_compile
--- a/.goodies/custom_path/java_compile
+++ b/.goodies/custom_path/java_compile
@@ -1,15 +1,38 @@
 #!/bin/bash
 
+error=""
+
+function compile
+{
+	local src_dir=$1
+	local out_dir=$2
+	local junit_dir=$3
+
+	rm out/* 2>/dev/null
+	files=$(find $src_dir -name \*.java)
+	# output=$(javac -cp $junit_dir $src_dir/*.java -d $out_dir 2>&1)
+	output=$(javac -d $out_dir -cp $junit_dir $files 2>&1)
+	if [ -z "$output" ]
+	then
+		return 0
+		#owo_print "Compiled successfuly!"
+	else
+		error=$output
+		return 1
+		#owo_print "Error compiling!"
+		#echo "$output"
+	fi
+}
+
 src_dir="src"
 out_dir="out"
-junit=$(echo lib/junit-platform-console-standalone-*.jar)
+junit_dir=$(echo lib/junit-platform-console-standalone-*.jar)
 
-rm out/* 2>/dev/null
-output=$(javac -cp $junit $src_dir/*.java -d $out_dir 2>&1)
-if [ -z "$output" ]
+compile $src_dir $out_dir $junit_dir
+if (( $? == 0 ))
 then
 	owo_print "Compiled successfuly!"
 else
 	owo_print "Error compiling!"
-	echo "$output"
+	echo "$error"
 fi
